version: "3.8"

services:
    training-platform:
        image: training-platform:latest
        build: ./training-platform/
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - platform-data:/data
        network_mode: host

    community-platform:
        image: community-platform:latest
        build: ./community-platform/
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - platform-data:/data
        ports:
            - "5900:5900"

    community-server:
        image: community-server:latest
        build: ./community-server/
        environment:
            - PLT_VERSION=8.3.24.1368
        volumes:
            - onecdb-server-data:/data
        ports:
            - "1540:1541"
            - "1560:1591"
        network_mode: host

    postgres-1c:
        image: postgres-1c:latest
        build: ./postgres-1c/
        environment:
            - PG_VERSION=1c-16
            - DEBUG=false
        ports:
            - "5433:5433"
        volumes:
            - type: volume
              source: postgres-1c-data
              target: /data
              volume:
                nocopy: true
            #- type: bind
            #  source: /mnt/SSD_2TB_2023/pgpro-data/1c-16
            #  target: ${PG_DATADIR}

volumes:
    platform-data:
    onecdb-server-data:
    postgres-1c-data:
