version: "3"

services:
  training-platform:
    image: training-platform:latest
    build: ./training-platform/
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host