version: "3"

services:
  training-platform:
    image: training-platform:latest
    build: ./training-platform/
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - onecdb-data:/data
    network_mode: host

volumes:
  onecdb-data: