services:
    training-platform:
        image: training-platform:latest
        build: ./training-platform/
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - platform-data:/data
        network_mode: host

    community-platform:
        image: community-platform:latest
        build: 
            context: ./community-platform/
            args:
                PLT_VERSION: 8.5.1.774
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - platform-data:/data
        ports:
            - "5900:5900"

    community-server:
        image: community-server:latest
        build: 
            context: ./community-server/
            args:
                PLT_VERSION: 8.5.1.774
        volumes:
            - onecdb-server-data:/var/1C
        ports:
            - "1540-1541:1540-1541"
            - "1560-1561:1560-1561"
        network_mode: host

    postgres-1c:
        image: postgres-1c:latest
        build: ./postgres-1c/
        environment:
            - PG_VERSION=${PG_VERSION:-1c-16}
            - PG_PORT=${PG_PORT:-5432}
        ports:
            - "${PG_PORT}:5432"
        volumes:
            - type: volume
              source: postgres-pro
              target: /var/lib/pgpro
              volume:
                nocopy: false

    nginx-1c:
        image: nginx-1c:latest
        build: ./nginx-1c/
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=${NGINX_PORT:-8080}
        ports:
            - "${NGINX_PORT:-8080}:80"
        volumes:
            - type: volume
              source: nginx-1c
              target: /etc/nginx/templates
              volume:
                nocopy: false

volumes:
    platform-data:
    onecdb-server-data:
    postgres-pro:
    nginx-1c:
