version: "3.8"

services:
    training-platform:
        image: training-platform:latest
        build: ./training-platform/
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - platform-data:/data
        network_mode: host

    community-platform:
        image: community-platform:latest
        build: ./community-platform/
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - platform-data:/data
        ports:
            - "5900:5900"

    community-server:
        image: community-server:latest
        build: ./community-server/
        environment:
            - PLT_VERSION=8.3.24.1368
        volumes:
            - onecdb-server-data:/data
        ports:
            - "1540-1541:1540-1541"
            - "1560-1561:1560-1561"
        network_mode: host

    postgres-1c:
        image: postgres-1c:latest
        build: ./postgres-1c/
        environment:
            - PG_VERSION=${PG_VERSION:-1c-16}
            - PG_PORT=${PG_PORT:-5433}
        ports:
            - "${PG_PORT}:5432"
        volumes:
            - type: volume
              source: postgres-pro
              target: /var/lib/pgpro
              volume:
                nocopy: false

volumes:
    platform-data:
    onecdb-server-data:
    postgres-pro:
