FROM ubuntu:22.04

ENV PLT_VERSION=8.3.24.1368
ENV PLT_USER=1000
ENV LANG ru_RU.UTF-8

ENV PLT_TARGET_INSATALL_FILE=setup-full-${PLT_VERSION}-x86_64.zip
ENV PLT_INSATALL_FILE=installAsRoot

RUN set -xe \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    libsoup2.4-dev \
    libcups2-dev \
    libenchant-2-dev \
    libgtk-3-dev \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    iputils-ping \
    gstreamer1.0-plugins-good gstreamer1.0-plugins-bad libsecret-1-0 libxslt1.1 geoclue-2.0 \
    iproute2 \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -r grp1cv8 --gid=${PLT_USER} \
    && useradd -r -g grp1cv8 --uid=${PLT_USER} --home-dir=/home/usr1cv8 --shell=/sbin/nologin usr1cv8 \
    && mkdir -p /home/usr1cv8 \
    && chown -R usr1cv8:grp1cv8 /home/usr1cv8

RUN mkdir -p /var/1C/licenses \
    && chown -R usr1cv8:grp1cv8 /var/1C/licenses

RUN mkdir -p /data /var/log/1C \
    && chown -R usr1cv8:grp1cv8 /data /var/log/1C

ADD target/*.tar.gz /install
RUN mkdir /install/bin
RUN unzip /install/${PLT_TARGET_INSATALL_FILE} -d /install/bin
RUN chmod +x /install/bin/installAsRoot \
    && /install/bin/installAsRoot \
    --mode unattended \
    --enable-components server,ws,server_admin,ru

RUN rm -rf /install

RUN ln -srf /lib/x86_64-linux-gnu/libenchant-2.so /lib/x86_64-linux-gnu/libenchant.so.1

ADD lic/ /var/1C/licenses
COPY conf/* /opt/1cv8/conf
RUN chown -R usr1cv8:grp1cv8 /var/1C

USER usr1cv8
VOLUME /home/usr1cv8
VOLUME /var/log/1C
EXPOSE 1540-1541 1560-1591

CMD /opt/1cv8/x86_64/${PLT_VERSION}/ragent -d /home/usr1cv8/.1cv8/1C/1cv8 -port 1540 -regport 1541 -range 1560:1591 -seclev 0 -pingPeriod 1000 -pingTimeout 5000 -debug