FROM ubuntu:22.04

ENV PLT_VERSION=8.3.23.1688
ENV LANG ru_RU.UTF-8

ARG onec_uid="999"
ARG onec_gid="999"
ARG onec_version="8.3.23.1688"

ADD target/training_8_3_23_1688_LinuxRun.tar.gz /install
#RUN cd /install && tar -xzf target/training_8_3_23_1688_LinuxRun.tar.gz && rm target/training_8_3_23_1688_LinuxRun.tar.gz

# RUN set -xe \
#     && apt-get update \
#     && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
#         libwebkitgtk-3.0-0 \
#     && rm -rf /var/lib/apt/lists/*
RUN set -xe \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    #--no-install-recommends \
        #libnss3-dev \
        #libgdk-pixbuf2.0-dev \
        #libgtk-3-dev \
        #libxss-dev \
        libsoup2.4-dev \
        libcups2-dev \
        #libenchant-2-dev \
        #libenchant-1-dev \
        libenchant-2-dev \
        libgtk-3-dev \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        libxt-dev \
        x11vnc \
        xvfb \
    && rm -rf /var/lib/apt/lists/*


RUN chmod +x /install/setup-training-8.3.23.1688-x86_64.run \
    && /install/setup-training-8.3.23.1688-x86_64.run

RUN rm -rf /install

RUN groupadd -r grp1cv8 --gid=$onec_gid \
  && useradd -r -g grp1cv8 --uid=$onec_uid --home-dir=/home/usr1cv8 --shell=/bin/bash usr1cv8 \
  && mkdir -p /home/usr1cv8/.1cv8 \
  && chown -R usr1cv8:grp1cv8 /home/usr1cv8

VOLUME /home/usr1cv8/.1cv8/

#ENV DISPLAY=:0
#USER 1000:1000

#CMD [ "onec-training" ]
CMD ["/opt/1cv8t/x86_64/8.3.23.1688/1cv8t"]